import React from "react";
import Head from 'next/head'
import Classes from 'styles/Resume.module.css';
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import MyGif from "../../public/AREmoji_20221029_123415_9044 (1).gif";
import NavBar from 'components/NavBar/NavBar';
import { FaHome, FaFileAlt, FaBars } from "react-icons/fa";
import { IoDocumentText, IoMail } from "react-icons/io5";
import SkillsSection from "components/Sections/Skills/Skills";
import WorkEx from "components/Sections/WorkEx/WorkEx";
import { Tab } from "@headlessui/react";
export default function Resume (props) {
  const percentage = 66;
  const [showMenu, setshowMenu] = React.useState(false);
    return (
      <div className={Classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Classes.main}>
        <div className="flex sm:flex-col lg:flex-row box-border sm:p-4 h-full">
        <Tab.Group>
          <NavBar page="resumePage" showMenu={showMenu}/>
          <Tab.Panels>
            <Tab.Panel><SkillsSection/></Tab.Panel>
            <Tab.Panel><WorkEx/></Tab.Panel>
            <Tab.Panel><WorkEx/></Tab.Panel>
            <Tab.Panel><WorkEx/></Tab.Panel>
          </Tab.Panels>
        </Tab.Group>
        </div>
        <div className="absolute bottom-0 w-[100vw] flex sm:hidden justify-end items-center">
        <button 
               className={"flex p-6 mx-6 my-4 shadow-shadow-only rounded-full z-menuButton " + (showMenu ? "bg-concave" : "bg-convex")}
               onClick={() => {
                setshowMenu(!showMenu);
               }}>
          <FaBars/>
        </button>
        </div>
      </main>
      </div>
  )
}

const iconsWanted = [
  "css3",
"exprejs",
"facebook",
"figma",
"git",
"github",
"gmail",
"html5",
"js",
"linkedin",
"mongodb",
"nodejs",
"reactjs",
"vscode"
]
   

/*

{iconsWanted.map((item) => {
              return (
              <div className={Classes.skillContainer}>
                <SkillFrame value={80}>
                  <SvgElements name={item}/> 
                </SkillFrame> 
              </div>
              )
            })}
*/